version: 2023.1  # Replace with your TeamCity version

projects:
  - name: "My Project"
    id: "MyProject"

    vcsRoots:
      - id: "MyGitRepo"
        name: "GitHub Repository"
        vcs:
          type: git
          url: "https://github.com/myorg/myrepo.git"
          branch: "refs/heads/main"

    buildTypes:
      - id: "InstallAndRun"
        name: "Install and Run"
        steps:
          # Step 1: Install Dependencies for the Binary
          - script:
              name: "Install Binary Dependencies"
              scriptContent: |
                sudo apt-get update
                sudo apt-get install -y <binary-dependency1> <binary-dependency2>
                echo "Binary dependencies installed."

          # Step 2: Install Python and Python Dependencies
          - script:
              name: "Install Python Dependencies"
              scriptContent: |
                sudo apt-get update
                sudo apt-get install -y python3 python3-pip
                pip3 install -r requirements.txt  # Ensure requirements.txt exists

          # Step 3: Run the Binary File
          - script:
              name: "Run Binary File"
              scriptContent: |
                chmod +x ./Moin
                ./Moin

          # Step 4: Run the Python Script
          - script:
              name: "Run Python Script"
              scriptContent: |
                python3 Moin.py
        requirements:
          # Ensure the build agent has necessary tools installed
          - contains: "env.PATH" "python3"
          - contains: "env.PATH" "apt-get"
